site_name: Learn A Little About SQL Development // Software Shinobi

docs_dir: 'book-content'

theme:

    name: readthedocs

    highlightjs: true

    hljs_languages:

        - yaml
        - rust
